name: Flutter Web

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'beta'
        
    - name: Enable Flutter web 
      run: flutter config --enable-web
      
    - name: Install dependencies
      run: flutter packages get
      
    - name: Build web
      run: flutter build web --base-href=/appFlutter/
      
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.token }}
        publish_dir: ./build/web